# tasks file
---
- name: configuration | fail
  fail:
    msg: "haproxy_global_nbproc is deprecated"
  when:
    - haproxy_version is version('2.3', '>=') and haproxy_version is version('2.5', '<')
    - haproxy_global_nbproc > 1
  tags:
    - haproxy-configuration-warn-or-fail

- name: configuration | update file
  template:
    src: "{{ haproxy_conf_template }}"
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0640
    validate: 'haproxy -f %s -c'
  notify: restart haproxy
  tags:
    - haproxy-configuration-update-file
